name: github_stars_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0
  sqflite: ^2.4.1
  path: ^1.9.0
  flutter_bloc: ^9.0.0
  google_fonts: ^6.2.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.1
  cloud_firestore: ^5.6.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  workmanager: ^0.5.2
  mailer: ^6.4.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
